### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by edwardtich1** [OxFF00FF/Hamster_Mayhem#11]
⚠️  HAMSTER_TOKEN не указан в вашем .env файле, либо вы указали его неверно.
⚠️  Все функции связанные с аккаунтом Hamster Kombat не доступны!

**Comment by OxFF00FF** [comment]
исправлено уже

**Comment by edwardtich1** [comment]
обновился. не работает

**Comment by OxFF00FF** [comment]
В папке src/data должен был создаться файл settungs.json с таким текстом
{
'send_to_group': False,
'save_to_file': False,
'apply_promo': False,
'hamster_token': None,
'account': 'HAMSTER_TOKEN_1'
}

**Comment by edwardtich1** [comment]
{
    "send_to_group": false,
    "save_to_file": false,
    "apply_promo": false,
    "hamster_token": false
}

вот такой у меня

**Comment by edwardtich1** [comment]
поправил руками

```
⚠️  HAMSTER_TOKEN не указан в вашем .env файле, либо вы указали его неверно.
⚠️  Все функции связанные с аккаунтом Hamster Kombat не доступны!

```

```
2024-08-26 20:37:27,010 - root - ERROR |  🚫  HTTP ошибка: 422 Client Error: Unprocessable Entity for url: https://api.hamsterkombatgame.io/auth/account-info  | Hamster.py - get_account_info() - 818
Обнаружен только 1 аккаунт в вашем .env файле. Используется `HAMSTER_TOKEN_1`
```

**Comment by edwardtich1** [comment]
3 |  🎮  My Clone Army     n/a/4  n/a · Осталось: n/a

**Comment by OxFF00FF** [comment]
обновил код, нужно удалить файл с настройками. создастся новый с нужными настройками при запуске
