### ISSUE TITLE
Генерация промокодов

### ISSUE THREAD

**Issue by russel5** [OxFF00FF/Hamster_Mayhem#13]
Постоянно ошибка, пробовал на винде и в линуксе, одно и тоже

`root - ERROR |  🚫  Произошла ошибка: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://api.gamepromo.io/promo/login-client'
Traceback (most recent call last):
  File "C:\Hamster_Mayhem-master\main.py", line 30, in <module>
    handle_main_menu_choice(choice)
  File "C:\Hamster_Mayhem-master\Src\Handlers.py", line 47, in handle_main_menu_choice
    handle_playground_menu_choice()
  File "C:\Hamster_Mayhem-master\Src\Handlers.py", line 147, in handle_playground_menu_choice
    asyncio.run(genetare_for_all_games())
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Hamster_Mayhem-master\Src\Generators.py", line 67, in genetare_for_all_games
    await asyncio.gather(*tasks)
  File "C:\Hamster_Mayhem-master\Src\Hamster.py", line 876, in get_promocodes
    promocodes = await __start_generate(count)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Hamster_Mayhem-master\Src\Hamster.py", line 871, in __start_generate
    keys = await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Hamster_Mayhem-master\Src\Hamster.py", line 835, in __key_generation
    client_token = await __get_client_token(session, client_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Hamster_Mayhem-master\Src\Hamster.py", line 789, in __get_client_token
    data = await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Hamster_Mayhem-master\venv\Lib\site-packages\aiohttp\client_reqrep.py", line 1199, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url='https://api.gamepromo.io/promo/login-client'

  | main.py - <module>()`

**Comment by Venia04** [comment]
@russel5 main.py точно в venv запускается?
у меня было такое когда просто в cmd попытался запустить main.py

**Comment by russel5** [comment]
Если в главном меню включить сохранение в файл, то ключи не сохраняются в файле.
И не всегда генерируются ключи в нужном количестве, вместо 4 бывает выдает 2 или 3, т.к. время генерации вышло, а ключ сервер выдать неуспел

**Comment by OxFF00FF** [comment]
Да, иногда меньше генерируется,  скорее всего из за нагрузки  на их сервер,  он просто не обработал запрос

**Comment by OxFF00FF** [comment]
> Если в главном меню включить сохранение в файл, то ключи не сохраняются в файле.

Сохранение в файл работает когда вы пропускаете пункт "применять промокоды" перед началом генерации

**Comment by OxFF00FF** [comment]
Ошибка  Attempt to decode JSON, с их стороны не приходит ответ в нужном формате,  просто начните еще раз или попробуйте через несколько минут

**Comment by russel5** [comment]
> > Если в главном меню включить сохранение в файл, то ключи не сохраняются в файле.
> 
> Сохранение в файл работает когда вы пропускаете пункт "применять промокоды" перед началом генерации

Я не включал опцию "применять промокоды"

**Comment by OxFF00FF** [comment]
да действительно не работало, из за ошибки в кодировке на винде при сохранении. обновите код, должно работать теперь.
если еще какие-то ошибки есть, пишите

**Comment by russel5** [comment]
сегодня при попытке покупки комбо. и надо скрипту как то подсказать что если уже карты куплены для комбо, то не надо их снова покупать. после ошибки снова попробовал выполнить комбо, дак бот снова купил те карты которые уже покупал и один хрен выплюнул эту ошибку, а карты у меня ох какие дорогие :)

2024-08-31 21:41:58,440 - root - ERROR |  🚫  HTTP ошибка: 400 Client Error: Bad Request for url: https://api.hamsterkombatgame.io/clicker/claim-daily-combo  | Hamster.py - complete_daily_combo() - 590

**Comment by Venia04** [comment]
@russel5 да, нужна проверка на купленные карты в комбо, такой же самый прикол сейчас произошел, надеюсь накоплю до следующего комбо))

**Comment by OxFF00FF** [comment]
Возможно чтото поменяли при получении награды, завтра проверю

**Comment by OxFF00FF** [comment]
Перед покупкой рекомендую проверить стоимость комбо и баланс. Там указана общая стоимость и профит,  чтобы понимать покупать ли комбо сегодня вообще

Команда # в главном меню

**Comment by russel5** [comment]
Мне хватало денег на 3 и последнюю карту, я больше потратил пока бот 2 раза одни и те же купил и 2 раза ошибку выдал. При нажатии на # - информация, бот показал только комбо из 2 карт которые сам и купил, информацию о 3 карте не показывал

**Comment by OxFF00FF** [comment]
> Мне хватало денег на 3 и последнюю карту, я больше потратил пока бот 2 раза одни и те же купил и 2 раза ошибку выдал. При нажатии на # - информация, бот показал только комбо из 2 карт которые сам и купил, информацию о 3 карте не показывал

Все понятно тогда, на сайте где я беру комбо неверно указали название(такое было пару раз)
поэтому 2 только куплены и не завершилось комбо. 
Если знаете как вычислять комбо, напишите
