### ISSUE TITLE
Предложение функционала

### ISSUE THREAD

**Issue by Venia04** [OxFF00FF/Hamster_Mayhem#14]
**Оч классный проект, респект**
Неплохо бы добавить автоматизацию по покупке ТОП эффективных карт исходя из наличия текущего таймера на каждой из карт и баланса.
К примеру:
1. Выбрать в меню купить карты
2. Пункт "выгодные"
3. Выводится список ТОПа **доступных** карт для покупки (основываясь на балансе и идет ли еще таймер карты).
4. Дать выбрать сколько карт из ТОПа купить.

**Comment by OxFF00FF** [comment]
я планировал такое сделать, чтобы можно было выбрать карту и она сама по кд покупалась, но пока думаю ка как такое можно реализовать

**Comment by OxFF00FF** [comment]
Добавил бота для автопрокачки

**Comment by Venia04** [comment]
Шикарно
