### ISSUE TITLE
опечатки/баги

### ISSUE THREAD

**Issue by Venia04** [OxFF00FF/Hamster_Mayhem#15]
### Первое:
Мне кажется, что в [UPDATE.bat](https://github.com/OxFF00FF/Hamster_Mayhem/blob/master/UPDATE.bat) нужно из этого -
```batchfile
........
echo Getting updates...

git pull

echo Project was updatet to latest version
.........
``` 
сделать это -
```batchfile
........
echo Getting updates...

git pull %REMOTE% master

echo Project was updatet to latest version
........
``` 

### Второе:
В main.py добавить 's' для пункта Settings

```python
26
27          choice = input(f"{DARK_GRAY}Выберите действие:\n{CYAN}(#/1/2/3/4/5/6/a/$/+/s/m/0):{RESET} ")
28
```

**Comment by Alex22891** [comment]
> ### Первое:
> Мне кажется, что в [UPDATE.bat](https://github.com/OxFF00FF/Hamster_Mayhem/blob/master/UPDATE.bat) нужно из этого -
> 
> ```batchfile
> ........
> echo Getting updates...
> 
> git pull
> 
> echo Project was updatet to latest version
> .........
> ```
> 
> сделать это -
> 
> ```batchfile
> ........
> echo Getting updates...
> 
> git pull %REMOTE% master
> 
> echo Project was updatet to latest version
> ........
> ```
> 
> ### Второе:
> В main.py добавить 's' для пункта Settings
> 
> ```python
> 26
> 27          choice = input(f"{DARK_GRAY}Выберите действие:\n{CYAN}(#/1/2/3/4/5/6/a/$/+/s/m/0):{RESET} ")
> 28
> ```

Пункты меню исправлены. По поводу UPDATE.BAT, вам ответит думаю @OxFF00FF

**Comment by OxFF00FF** [comment]
git pull %REMOTE% master

Думаете будет лучше если обновление только с мастер ветки будет браться?

**Comment by Venia04** [comment]
Так обновление у меня вообще не берется.
Видит две ветки и не знает откуда брать, с ошибкой.
А так мастер берет и всё, ноль вопросов

**Comment by OxFF00FF** [comment]
Все Понял,  спасибо

**Comment by OxFF00FF** [comment]
Я делаю git pull с мастера,  если нет папки .git, (это для тех кто архив скачал)
и потом обычный git pull работал без вопросов
