### ISSUE TITLE
new playground game detected: Stone Age

### ISSUE THREAD

**Issue by Endijuan33** [OxFF00FF/Hamster_Mayhem#18]
please update the script to add stone age games 

"b4170868-cef0-424f-8eb9-be0622e8e8e3": {
        "name": "Chain Cube 2048",
        "appToken": "d1690a07-3780-4068-810f-9b5bbf2931b2",
        "promoId": "b4170868-cef0-424f-8eb9-be0622e8e8e3",
        "userAgent": "UnityPlayer/2022.3.20f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)",
        "x-unity-version": "2022.3.20f1",
        "clientOrigin": "android",
        "clientIdType": "uuid",
        "clientVersion": "1.78.42",
        "eventIdType": "uuid",
        "eventOrigin": "undefined",
        "eventType": "cube_sent",
        "delay": 20,
        "retry_delay": 20,
    },
    "c4480ac7-e178-4973-8061-9ed5b2e17954": {
        "name": "Train Miner",
        "appToken": "82647f43-3f87-402d-88dd-09a90025313f",
        "promoId": "c4480ac7-e178-4973-8061-9ed5b2e17954",
        "userAgent": "UnityPlayer/2022.3.20f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)",
        "x-unity-version": "2022.3.20f1",
        "clientOrigin": "android",
        "clientIdType": "32str",
        "clientVersion": "2.6.4",
        "eventIdType": "uuid",
        "eventOrigin": "undefined",
        "eventType": "hitStatue",
        "delay": 120,
        "retry_delay": 20,
    },
    "dc128d28-c45b-411c-98ff-ac7726fbaea4": {
        "name": "Merge Away",
        "appToken": "8d1cc2ad-e097-4b86-90ef-7a27e19fb833",
        "promoId": "dc128d28-c45b-411c-98ff-ac7726fbaea4",
        "userAgent": None,
        "x-unity-version": None,
        "clientOrigin": "android",
        "clientIdType": "type1",
        "clientVersion": None,
        "eventIdType": "uuid",
        "eventOrigin": "undefined",
        "eventType": "spend-energy",
        "delay": 20,
        "retry_delay": 20,
    },
    "61308365-9d16-4040-8bb0-2f4a4c69074c": {
        "name": "Twerk Race",
        "appToken": "61308365-9d16-4040-8bb0-2f4a4c69074c",
        "promoId": "61308365-9d16-4040-8bb0-2f4a4c69074c",
        "userAgent": "UnityPlayer/2021.3.15f1 (UnityWebRequest/1.0, libcurl/7.84.0-DEV)",
        "x-unity-version": "2021.3.15f1",
        "clientOrigin": "android",
        "clientIdType": "type1",
        "clientVersion": None,
        "eventIdType": "StartLevel",
        "eventOrigin": "undefined",
        "eventType": None,
        "delay": 20,
        "retry_delay": 20,
    },
    "2aaf5aee-2cbc-47ec-8a3f-0962cc14bc71": {
        "name": "Polysphere",
        "appToken": "2aaf5aee-2cbc-47ec-8a3f-0962cc14bc71",
        "promoId": "2aaf5aee-2cbc-47ec-8a3f-0962cc14bc71",
        "userAgent": "UnityPlayer/2021.3.39f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)",
        "x-unity-version": "2021.3.39f1",
        "clientOrigin": "android",
        "clientIdType": "uuid",
        "clientVersion": "1.15.301",
        "eventIdType": "uuid",
        "eventOrigin": "undefined",
        "eventType": "test",
        "delay": 20,
        "retry_delay": 20,
    },
    "ef319a80-949a-492e-8ee0-424fb5fc20a6": {
        "name": "Mow and Trim",
        "appToken": "ef319a80-949a-492e-8ee0-424fb5fc20a6",
        "promoId": "ef319a80-949a-492e-8ee0-424fb5fc20a6",
        "userAgent": "UnityPlayer/2021.3.17f1 (UnityWebRequest/1.0, libcurl/7.84.0-DEV)",
        "x-unity-version": "2021.3.17f1",
        "clientOrigin": "android",
        "clientIdType": "type1",
        "clientVersion": None,
        "eventIdType": "StartLevel",
        "eventOrigin": "undefined",
        "eventType": None,
        "delay": 120,
        "retry_delay": 60,
    },
    "b2436c89-e0aa-4aed-8046-9b0515e1c46b": {
        "name": "Zoopolis",
        "appToken": "b2436c89-e0aa-4aed-8046-9b0515e1c46b",
        "promoId": "b2436c89-e0aa-4aed-8046-9b0515e1c46b",
        "userAgent": "UnityPlayer/2022.3.15f1 (UnityWebRequest/1.0, libcurl/8.4.0-DEV)",
        "x-unity-version": "2022.3.15f1",
        "clientOrigin": "android",
        "clientIdType": "32str",
        "clientVersion": "1.2.7",
        "eventIdType": "uuid",
        "eventOrigin": "undefined",
        "eventType": "ZoopolisEvent",
        "delay": 30,
        "retry_delay": 45,
    },
    "112887b0-a8af-4eb2-ac63-d82df78283d9": {
        "useNewApi": True,
        "name": "Fluff Crusade",
        "appToken": "112887b0-a8af-4eb2-ac63-d82df78283d9",
        "promoId": "112887b0-a8af-4eb2-ac63-d82df78283d9",
        "userAgent": "UnityPlayer/2022.3.27f1 (UnityWebRequest/1.0, libcurl/8.5.0-DEV)",
        "x-unity-version": "2022.3.27f1",
        "clientOrigin": "deviceid",
        "clientIdType": "uuid",
        "clientVersion": None,
        "eventIdType": "uuid",
        "eventOrigin": "undefined",
        "eventType": None,
        "delay": 180,
        "retry_delay": 180,
    },
    "e68b39d2-4880-4a31-b3aa-0393e7df10c7": {
        "useNewApi": True,
        "name": "Tile Trio",
        "appToken": "e68b39d2-4880-4a31-b3aa-0393e7df10c7",
        "promoId": "e68b39d2-4880-4a31-b3aa-0393e7df10c7",
        "userAgent": "UnityPlayer/2020.3.48f1 (UnityWebRequest/1.0, libcurl/7.84.0-DEV)",
        "x-unity-version": "2020.3.48f1",
        "clientOrigin": "deviceid",
        "clientIdType": "7digStr",
        "clientVersion": "12.4.57",
        "eventIdType": "uuid",
        "eventOrigin": "undefined",
        "eventType": "gt_progress",
        "delay": 30,
        "retry_delay": 30,
    },
    "04ebd6de-69b7-43d1-9c4b-04a6ca3305af": {
        "useNewApi": True,
        "name": "Stone Age",
        "appToken": "04ebd6de-69b7-43d1-9c4b-04a6ca3305af",
        "promoId": "04ebd6de-69b7-43d1-9c4b-04a6ca3305af",
        "userAgent": None,
        "x-unity-version": None,
        "clientOrigin": "android",
        "clientIdType": "16UpStr",
        "clientVersion": "1.113.113",
        "eventIdType": "7dig",
        "eventOrigin": "undefined",
        "eventType": None,
        "delay": 30,
        "retry_delay": 60,
    }

I hope this helps a little🙏🏻

**Comment by Alex22891** [comment]
The game has been added
