### ISSUE TITLE
Spinner_list error

### ISSUE THREAD

**Issue by Venia04** [OxFF00FF/Hamster_Mayhem#19]
![image](https://github.com/user-attachments/assets/13873bf4-8b1e-454c-8a69-0778c93da9c9)

**Comment by Venia04** [comment]
![image](https://github.com/user-attachments/assets/36da4862-2523-402d-a840-07d5a744276c)
и в целом что-то непонятное происходит со спиннерами

**Comment by OxFF00FF** [comment]
Просто list используй

**Comment by Venia04** [comment]
@OxFF00FF тогда стоит это указать в меню) не сказать что прям очевидно)

**Comment by OxFF00FF** [comment]
> @OxFF00FF тогда стоит это указать в меню) не сказать что прям очевидно)

Я это в редми указал  😁
