### ISSUE TITLE
Покупка рентабельных карт

### ISSUE THREAD

**Issue by prokosha002** [OxFF00FF/Hamster_Mayhem#20]
День добрый!
Очень понравилась функция показа 20-ти самых выгодных карт.
Хочу внести свою лепту:
1.  Раньше было видно время окупаемости исходя из прибыли новой купленной карты, а не всех карт в совокупности. На мой взгляд, первый вариант был правильнее, чем сейчас.
2.  Была бы просто не заменимая фича покупки самых рентабельных карт не `+ID_Карты`,  а, к примеру, +5 - что бы означало покупка пяти самых выгодных карт, соотвественно, +20 - покупка всех карт из списка.

**Comment by OxFF00FF** [comment]
1. Время окупаемости указано сейчас. Раньше был неверный расчет времени,  но сейчас все правильно 
2. Многие просили такое,  я думаю сделать так чтобы прям из этого списка можно было купить карту

**Comment by OxFF00FF** [comment]
> 2. Была бы просто не заменимая фича покупки самых рентабельных карт не `+ID_Карты`,  а, к примеру, +5 - что бы означало покупка пяти самых выгодных карт, соотвественно, +20 - покупка всех карт из списка.

добавил сегодня
