### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by eXPoZii** [OxFF00FF/Hamster_Mayhem#24]
![{094BFF20-24FD-4779-9C08-FD378E4C8308}](https://github.com/user-attachments/assets/9a01de2e-0de3-4c68-8d2b-cf89cbd533c9)
After 30 min dont upgrade the card

**Comment by eXPoZii** [comment]
![{45AEE868-E8BD-4624-A4E1-9D0DB7073947}](https://github.com/user-attachments/assets/593215a6-1aec-4d88-bd1a-e11ba82021e8)
And got this error but bot work

**Comment by eXPoZii** [comment]
![{89E70AEB-27FB-4D27-BBB6-F503594A7649}](https://github.com/user-attachments/assets/4c939e07-99f7-42b1-aa71-5e0599da5730)

**Comment by Venia04** [comment]
> ![{45AEE868-E8BD-4624-A4E1-9D0DB7073947}](https://private-user-images.githubusercontent.com/175480551/367573744-593215a6-1aec-4d88-bd1a-e11ba82021e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDU2MzksIm5iZiI6MTcyNjQwNTMzOSwicGF0aCI6Ii8xNzU0ODA1NTEvMzY3NTczNzQ0LTU5MzIxNWE2LTFhZWMtNGQ4OC1iZDFhLWUxMWJhODIwMjFlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxMzAyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODYwNmUxODBiMTBiMzgxNDgxMGU1YzEzM2NiN2ZjODBkNGRiN2ExMzgwYjJmMDgzYTYwM2VmYzFhMWFjM2VhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MVlR9xBVbbipfzUUf47gev6c-pwi9rTiAHUNaWODYQA) And got this error but bot work

This error happens because you didn't specified your bot token and chat_id in .env file.
