### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by andrei4ik1997** [OxFF00FF/Hamster_Mayhem#26]
Hamster_Mayhem\Src\db_SQlite.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by Venia04** [comment]
@andrei4ik1997 
delete "venv" folder
run UPDATE.bat
run INSTALL.bat

**Comment by andrei4ik1997** [comment]
@Venia04 Thank you, this solved the problem
