### ISSUE TITLE
Добавили две новые игры

### ISSUE THREAD

**Issue by edwardtich1** [OxFF00FF/Hamster_Mayhem#7]
Mow and Trim
Promo id: ef319a80-949a-492e-8ee0-424fb5fc20a6
Token: ef319a80-949a-492e-8ee0-424fb5fc20a6
Interval: 20

Mud Racing
Promo id: 8814a785-97fb-4177-9193-ca4180ff9da8
Token: 8814a785-97fb-4177-9193-ca4180ff9da8
Interval: 20

**Comment by OxFF00FF** [comment]
уже добавил

**Comment by edwardtich1** [comment]
Готово? Можно обновляться?

**Comment by OxFF00FF** [comment]
да
