### ISSUE TITLE
Окупаемость карт в часах

### ISSUE THREAD

**Issue by edwardtich1** [OxFF00FF/Hamster_Mayhem#9]
Окупаемость карт в часах

![2024-08-24_09-30-04](https://github.com/user-attachments/assets/fcec2d53-a78b-487a-b31d-739256ff7940)

**Comment by edwardtich1** [comment]
прибыль в час тоже неправильно считает

**Comment by OxFF00FF** [comment]
> прибыль в час тоже неправильно считает

исправил сегодня формулы. Теперь корректно отображается
